### ISSUE TITLE
pdf rotate error

### ISSUE THREAD

**Issue by nicdnepr** [czproject/pdf-rotate#1]
[AHCLCYIYH.pdf](https://github.com/czproject/pdf-rotate/files/10139029/AHCLCYIYH.pdf)
this pdf rotate with error
the code is 
```
use CzProject\PdfRotate\PdfRotate;

$pdf = new PdfRotate;
$sourceFile = 'in.pdf';
$outputFile = 'out.pdf';

$pdf->rotatePdf($sourceFile, $outputFile, $pdf::DEGREES_180);
```
the result is 
[out.pdf](https://github.com/czproject/pdf-rotate/files/10139032/out.pdf)

**Comment by janpecha** [comment]
Hello, thanks for report! Fixed in version **2.0.1**.
