### ISSUE TITLE
when i use this package in laravel it showing some error please resolve ASP

### ISSUE THREAD

**Issue by amitdevteams** [czproject/pdf-rotate#2]
Declaration of setasign\Fpdi\FpdfTplTrait::setPageFormat($size, $orientation) must be compatible with TCPDF::setPageFormat($format, $orientation = 'P') {"exception":"[object]

**Comment by amitdevteams** [comment]
This is my controller function


public function convert(Request $request){

        Log::info('request me kya aa rha hai'.$request->pdf_file);
        try {
            if ($request->hasFile('pdf_file')) {
                $pdfFile = $request->file('pdf_file');
    
                if ($pdfFile->isValid()) {
                    $originalFilename = time() . '-' . $pdfFile->getClientOriginalName();
                    $pdfFile->move(public_path(), $originalFilename);
                    $sourceFile = public_path($originalFilename);
                    $outputFile = public_path('rotate.pdf');
    
                    $pdf = new PdfRotate();
                    $success = $pdf->rotatePdf($sourceFile, $outputFile, PdfRotate::DEGREES_90);
    
                    if ($success) {
                        // Delete the original file to save disk space
                        unlink($sourceFile);
    
                        return response()->download($outputFile);
                    } else {
                        throw new Exception('Failed to rotate PDF file');
                    }
                } else {
                    throw new Exception('Invalid PDF file');
                }
            } else {
                throw new Exception('PDF file not found');
            }
        } catch (Exception $e) {
            Log::error($e->getMessage());
            return response()->json(['error' => $e->getMessage()]);
        }
    }

**Comment by janpecha** [comment]
Hello, this library is only wrapper around Setasign\FPDI, please report issue in https://github.com/Setasign/FPDI
